### ISSUE TITLE
NameError for `moves` in Py3 conditional

### ISSUE THREAD

**Issue by ckald** [rossant/ipycache#22]
At this line: https://github.com/rossant/ipycache/blob/master/ipycache.py#L32

I don't see what it is supposed to be, so I'm just pointing out a bug

**Comment by ihrke** [comment]
I think that is an artifact copied over from the `six` library (they define `moves` to be a list of modules that have changed bw python2 and 3). I guess we should work on `python3` compatibility at some point.

**Comment by rossant** [comment]
I don't think the library has ever been tested on Python 3. Some of the code already contains some Py3-compat functionality to make the transition a bit smoother. It shouldn't be too difficult to port the code to Python 3 now.
