### ISSUE TITLE
Use of cloudpickle

### ISSUE THREAD

**Issue by fabianrost84** [rossant/ipycache#34]
Warning: I'm not much of a python developer!
I just tried to include the use of cloudpickle in case pickle fails:
https://github.com/fabianrost84/ipycache
For me this comes very handy as I often like to pickle lambda functions. 
What do you think about including the (possibly optional) use of cloudpickle in ipcache?
I'm also not sure how this relates to https://github.com/rossant/ipycache/issues/28.

**Comment by rossant** [comment]
+1 for me, I or @ihrke would be happy to review your PR!

**Comment by fabianrost84** [comment]
PR created
