### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by callzhang** [rossant/ipycache#38]
File "<ipython-input-134-b6c6306772b0>", line 3
    %%cache company_facebook_data.pkl company_facebook_data
    ^
SyntaxError: invalid syntax

I am using python 3.4

**Comment by fabianrost84** [comment]
And which notebook version are you using? Typically this error happens to me, when the `%%cache` magic is not the first line of the cell. This seems to be the case for you, because the error message says `line 3`.

**Comment by callzhang** [comment]
You are right. I figured it out. Thanks!
