### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by jakirkham** [rossant/ipycache#41]
We were adding `ipycache` to [conda-forge](http://conda-forge.github.io/), but there seems to be a bit of confusion about the license. Is this intended to be BSD 3-clause?

cc @jochym

**Comment by rossant** [comment]
Thank you for your interest in ipycache. Unfortunately I don't have enough time right now to manage this project, would you be interested in getting commit access?

**Comment by jakirkham** [comment]
Thanks for asking. Though that seems like a better question for @jochym. Assuming you are amenable to this @rossant, do you have any interest in helping maintain `ipycache`, @jochym?

In any event, a clarification on the license would be nice. Though, to be honest, I have forgotten what the point of confusion was.

**Comment by mbrukman** [comment]
@jakirkham — was this already resolved previously, or is there still confusion over the license?

Per https://github.com/rossant/ipycache/blob/master/LICENSE.md, GitHub is classifying this as:

> BSD 3-Clause "New" or "Revised" License

Are you asking that `setup.py` is updated to use a more specific SPDX identifier for the BSD 3-clause license vs simply the string "BSD" as it says now? Or are you looking for something else?

**Comment by jakirkham** [comment]
@mbrukman, sorry I don't really know. It has been a long time since this issue was opened and have unfortunately forgotten the context of the confusion

@jochym, is there anything remaining to do here from your standpoint?

**Comment by jochym** [comment]
Sorry for not responding. 
1. The license is BSD-3-clause, I believe. It should be as the original author selected.
2. As for maintenance.  I can adopt the package but cannot promise intensive development.

**Comment by rossant** [comment]
Sorry I haven't been closely following this discussion, but as the original author, I shall say I'm happy with the license being updated to match whatever is currently considered as standard practice in similar Python projects.

**Comment by mbrukman** [comment]
@jakirkham — re: `s/BSD/BSD-3-Clause/` in `setup.py` — sounds good, will do shortly!

@jochym — FWIW, I've signed up to be a co-maintainer; you're welcome to join the party as well if you wish!

**Comment by jakirkham** [comment]
Thanks for all the work here @mbrukman ! 😀
