### ISSUE TITLE
Is it possible to keep previous output (e.g., figures) when re-run (and skip) a cached cell?

### ISSUE THREAD

**Issue by herrlich10** [rossant/ipycache#5]
At present, the output will be replaced by "Skipped the cell's code and loaded variables...", and all the figures are gone.

I've tried to set the default value of --verbose to False in the source code (I don't know how to disable a default True option). This will disable any new print out, but still clear previous output.

I think support for long-running cell (like this `%%cache` magic) is a major feature that ipython notebook lacks at present. If some cells can be skipped but left their output figures intact when re-run the entire notebook, it would be very useful, at least for data analysis purpose. See my [question](http://stackoverflow.com/questions/19309287/how-to-intermittently-skip-certain-cells-when-running-ipython-notebook) at stackoverflow.

Thanks, rossant! I really like your project (and register an account just for making this comment:)

**Comment by yasirroni** [comment]
> Thanks, it works! I had to add:
> 
> ```
> def __init__(self, shell=None):
>     Magics.__init__(self, shell)
>     Configurable.__init__(self, config=shell.config)
> ```

I'm lost with this discussion.

So, back to the main question, how to achive **"Is it possible to keep previous output (e.g., figures) when re-run (and skip) a cached cell?"**

Using tags? magic? metadata? A simple skip and preserve last output when we press run all.

Sadly, even make cell meta data untrested not work:

```
{
    "trusted": false,
    "tags": [],
    "editable": false,
    "deletable": false
}
```
