### ISSUE TITLE
Configure travisCI with nosetests

### ISSUE THREAD

**Issue by rossant** [rossant/ipycache#6]
Python 2.7 and 3.3
Latest stable IPython and master

**Comment by ihrke** [comment]
I don't think I can add travis builds for rossant/ipycache. Seems you need administrative rights and I got only writing petmissions.

**Comment by rossant** [comment]
Are you sure? You've been given full access to the repo.

Otherwise what should I do exactly?

**Comment by ihrke** [comment]
The repository does not show up in my travis account and I don't have a settings icon for the repo. I think that is something only the owner can do. Basically you just need to go to http://travis-ci.org, log in with your github credentials and check the box next to the rossant/ipycache repo. That should enable an automated test starting with the next push.

**Comment by rossant** [comment]
OK, I just did this. Is it working now?

**Comment by ihrke** [comment]
Yep. I added a badge to the readme.
